<?php

/**
 * BaseBgEnRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BgWord $BgWord
 * @property EnWord $EnWord
 * 
 * @method BgWord       getBgWord() Returns the current record's "BgWord" value
 * @method EnWord       getEnWord() Returns the current record's "EnWord" value
 * @method BgEnRelation setBgWord() Sets the current record's "BgWord" value
 * @method BgEnRelation setEnWord() Sets the current record's "EnWord" value
 * 
 * @package    mathdict
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBgEnRelation extends Relation
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('bg_en_relation');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BgWord', array(
             'local' => 'from_word_id',
             'foreign' => 'id'));

        $this->hasOne('EnWord', array(
             'local' => 'to_word_id',
             'foreign' => 'id'));
    }
}