<?php

/**
 * BaseBgWord
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property Doctrine_Collection $DeWords
 * @property Doctrine_Collection $EnWords
 * @property Doctrine_Collection $BgDeRelations
 * @property Doctrine_Collection $BgEnRelations
 *
 * @method Doctrine_Collection getDeWords()       Returns the current record's "DeWords" collection
 * @method Doctrine_Collection getEnWords()       Returns the current record's "EnWords" collection
 * @method Doctrine_Collection getBgDeRelations() Returns the current record's "BgDeRelations" collection
 * @method Doctrine_Collection getBgEnRelations() Returns the current record's "BgEnRelations" collection
 * @method BgWord              setDeWords()       Sets the current record's "DeWords" collection
 * @method BgWord              setEnWords()       Sets the current record's "EnWords" collection
 * @method BgWord              setBgDeRelations() Sets the current record's "BgDeRelations" collection
 * @method BgWord              setBgEnRelations() Sets the current record's "BgEnRelations" collection
 *
 * @package    mathdict
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBgWord extends Word
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('bg_word');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DeWord as DeWords', array(
             'refClass' => 'BgDeRelation',
             'local' => 'from_word_id',
             'foreign' => 'id'));

        $this->hasMany('EnWord as EnWords', array(
             'refClass' => 'BgEnRelation',
             'local' => 'from_word_id',
             'foreign' => 'id'));

        $this->hasMany('BgDeRelation as BgDeRelations', array(
             'local' => 'id',
             'foreign' => 'from_word_id'));

        $this->hasMany('BgEnRelation as BgEnRelations', array(
             'local' => 'id',
             'foreign' => 'from_word_id'));
    }
}