<?php

/**
 * BaseDeEnRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property DeWord $DeWord
 * @property EnWord $EnWord
 * 
 * @method DeWord       getDeWord() Returns the current record's "DeWord" value
 * @method EnWord       getEnWord() Returns the current record's "EnWord" value
 * @method DeEnRelation setDeWord() Sets the current record's "DeWord" value
 * @method DeEnRelation setEnWord() Sets the current record's "EnWord" value
 * 
 * @package    mathdict
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDeEnRelation extends Relation
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('de_en_relation');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DeWord', array(
             'local' => 'from_word_id',
             'foreign' => 'id'));

        $this->hasOne('EnWord', array(
             'local' => 'to_word_id',
             'foreign' => 'id'));
    }
}