<?php

/**
 * BaseDeWord
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property Doctrine_Collection $BgWords
 * @property Doctrine_Collection $EnWords
 * @property Doctrine_Collection $BgDeRelations
 * @property Doctrine_Collection $DeEnRelations
 *
 * @method Doctrine_Collection getBgWords()       Returns the current record's "BgWords" collection
 * @method Doctrine_Collection getEnWords()       Returns the current record's "EnWords" collection
 * @method Doctrine_Collection getBgDeRelations() Returns the current record's "BgDeRelations" collection
 * @method Doctrine_Collection getDeEnRelations() Returns the current record's "DeEnRelations" collection
 * @method DeWord              setBgWords()       Sets the current record's "BgWords" collection
 * @method DeWord              setEnWords()       Sets the current record's "EnWords" collection
 * @method DeWord              setBgDeRelations() Sets the current record's "BgDeRelations" collection
 * @method DeWord              setDeEnRelations() Sets the current record's "DeEnRelations" collection
 *
 * @package    mathdict
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDeWord extends Word
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('de_word');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BgWord as BgWords', array(
             'refClass' => 'BgDeRelation',
             'local' => 'to_word_id',
             'foreign' => 'id'));

        $this->hasMany('EnWord as EnWords', array(
             'refClass' => 'DeEnRelation',
             'local' => 'from_word_id',
             'foreign' => 'id'));

        $this->hasMany('BgDeRelation as BgDeRelations', array(
             'local' => 'id',
             'foreign' => 'to_word_id'));

        $this->hasMany('DeEnRelation as DeEnRelations', array(
             'local' => 'id',
             'foreign' => 'from_word_id'));
    }
}