<?php

/**
 * BaseRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $from_word_id
 * @property integer $to_word_id
 * 
 * @method integer  getFromWordId()   Returns the current record's "from_word_id" value
 * @method integer  getToWordId()     Returns the current record's "to_word_id" value
 * @method Relation setFromWordId()   Sets the current record's "from_word_id" value
 * @method Relation setToWordId()     Sets the current record's "to_word_id" value
 * 
 * @package    mathdict
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseRelation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('relation');
        $this->hasColumn('from_word_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '2',
             ));
        $this->hasColumn('to_word_id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}