<?php

/**
 * BaseBgDeRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BgWord $BgWord
 * @property DeWord $DeWord
 * 
 * @method BgWord       getBgWord() Returns the current record's "BgWord" value
 * @method DeWord       getDeWord() Returns the current record's "DeWord" value
 * @method BgDeRelation setBgWord() Sets the current record's "BgWord" value
 * @method BgDeRelation setDeWord() Sets the current record's "DeWord" value
 * 
 * @package    mathdict
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBgDeRelation extends Relation
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('bg_de_relation');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('BgWord', array(
             'local' => 'from_word_id',
             'foreign' => 'id'));

        $this->hasOne('DeWord', array(
             'local' => 'to_word_id',
             'foreign' => 'id'));
    }
}