<?php

/**
 * BaseWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $wp_article
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getWpArticle()  Returns the current record's "wp_article" value
 * @method Word    setId()         Sets the current record's "id" value
 * @method Word    setName()       Sets the current record's "name" value
 * @method Word    setWpArticle()  Sets the current record's "wp_article" value
 * 
 * @package    mathdict
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('word');
        $this->hasColumn('id', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '2',
             ));
        $this->hasColumn('name', 'string', 160, array(
             'type' => 'string',
             'length' => '160',
             ));
        $this->hasColumn('wp_article', 'string', 160, array(
             'type' => 'string',
             'length' => '160',
             ));


        $this->index('name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}